require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    UHaul: uhaul
